name: comment-store
services:
    # app:
    #     image: comment-store-app:latest
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     develop:
    #         watch:
    #             - action: rebuild
    #               path: /app
    #     ports:
    #         - "8080:8080"
    db:
        container_name: "postgresql-db"
        image: postgres:16.4
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: commentstore
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U root -d commentstore"]
            interval: 3s
            timeout: 5s
            retries: 5
        volumes:
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
